#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 1
#define MEMORY_ALLOCATION_ERROR -1
#define INVALID_POSITION_ERROR -2
#define EMPTY_STRUCTURE_ERROR -3
#define FULL_STRUCTURE_ERROR -4
#define ELEMENT_NOT_FOUND_ERROR -5

#endif